### ISSUE TITLE
Unable to login to content server with seed users

### ISSUE THREAD

**Issue by pramttl** [privly/privly-flask#17]
I ran the `python manage.py seed` command. But I was unable to login to the Content server [1] with any of the default users, admin@priv.ly, development@priv.ly, etc

The content server is running but it shows the error `Bad username or password. Too many failed attempts will lock the account` on the top.

[1] http://localhost:3000/static/privly-applications/Login/new.html

Then I tried to run the seed command again and got this error:

```
sqlalchemy.exc.IntegrityError: (IntegrityError) UNIQUE constraint failed: user.email u'INSERT INTO user (email, password, created, updated, confirmation_token, verified) VALUES (?, ?, ?, ?, ?, ?)' ('admin@priv.ly', 'pbkdf2:sha512:1000$BbCfyrMbshutruml07js9jCS7ZDUSJ4WWz6kLYOJWDK0xd6u6b3Nc55nLrGQDgQqu8GRlNi5KqiHxqBYU7seFynpHlWg5Xis6Btjsk4TlgiNni2yLtCvh5TCELN7ikxF$31a5b07ed2005316b0bcf70fbdeecfe6c3e0d252837eb3d98c083e769256d9cf4c2d5341f49931a560d20ab256939fe54361ac1b501a8befcc00633e8bdebbe2', '2015-02-11 14:11:03.345012', '2015-02-11 14:11:03.345012', 'tFcYYF5nKmttgxq01M6VWV0Y1EHhe006', 0)
```

If the credentials are created already, I should be allowed to login, if not I should be able to create them. I am confused why this isn't working for me.

**Comment by pramttl** [comment]
Strange, I restarted the server again and was able to login.

**Comment by spectralsun** [comment]
I followed the guide in the README.md and had no issue logging in as admin@priv.ly. I think your flask development server might have had a stale database connection or you mis-typed the login.
